# Generated by Django 3.0.4 on 2020-03-20 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_profile_is_staff'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_staff',
            new_name='is_profile',
        ),
    ]
