# Generated by Django 3.0.4 on 2020-03-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0004_town'),
    ]

    operations = [
        migrations.RenameField(
            model_name='town',
            old_name='name',
            new_name='town_name',
        ),
        migrations.AlterField(
            model_name='town',
            name='town_id',
            field=models.ManyToManyField(blank=True, to='portal.Profile'),
        ),
    ]
