# Generated by Django 3.0.4 on 2020-03-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200316_0135'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
